version: '2.1'
services:
  www-integration:
    privileged: true
    network_mode: 'host'
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - www-code
  www-code:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn --cwd /workspace/app dev
    volumes:
      - '$PWD/artifacts:/workspace/artifacts'
